#!/usr/bin/env bash

# Install Drive Monitor files to operational directories

set -e

if [ $(id -u) -ne 0 ]; then
    echo "Root privileges are required for running $0."
    exit 1
fi

MY_DIR=$(dirname $0)
systemd='/etc/systemd/system/'
unit='drive-monitor.service'
timer='drive-monitor.timer'
sbin='/usr/local/sbin/'
script='drive-monitor'
sbinscript="$sbin/$script"

cp "$MY_DIR/$unit" "$systemd"
cp "$MY_DIR/$timer" "$systemd"
cp "$MY_DIR/$script" "$sbin"

chmod u+x "$sbinscript"

systemctl daemon-reload
